name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Вывод структуры для отладки (опционально)
      - name: List repository files
        run: ls -R .

      # 3. Настраиваем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 4. Обновляем pip и устанавливаем build
      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      # 5. Устанавливаем зависимости проекта
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 6. Собираем пакет в wheel/sdist
      - name: Build distribution
        run: python -m build .

      # 7. Архивируем артефакты сборки
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  security:
    name: Static Analysis (Bandit)
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Клонируем код снова для этой job
      - name: Checkout code
        uses: actions/checkout@v4

      # Устанавливаем Bandit
      - name: Install Bandit
        run: pip install bandit

      # Запускаем сканирование
      - name: Run Bandit
        run: bandit -r . -f github
