name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4  # клонирует репозиторий в $GITHUB_WORKSPACE :contentReference[oaicite:0]{index=0}

      # 2. Вывод структуры директорий для отладки
      - name: List files
        run: ls -R .                # покажет, где лежит requirements.txt :contentReference[oaicite:1]{index=1}

      # 3. Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'    # выбираем последнюю версию 3.x :contentReference[oaicite:2]{index=2}

      # 4. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # если файл в корне; иначе скорректируйте путь

      # 5. Сборка пакета
      - name: Build wheel
        run: python -m build .     # создаёт артефакты в папке dist/

      # 6. Архивация сборки
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4  # v4 — единственная поддерживаемая на GitHub.com версия :contentReference[oaicite:3]{index=3}
        with:
          name: dist
          path: dist/

  security:
    name: Static Code Analysis (Bandit)
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 1. Клонирование для второй задачи
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Установка Bandit
      - name: Install Bandit
        run: pip install bandit

      # 3. Запуск статического анализа
      - name: Run Bandit security scan
        run: bandit -r . -f github
